#!/usr/bin/env python3
# asmdal_tables.py - extract the opcode and JSYS tables from the original
# CP-6 PL/6 source (ASMDAL_SI61.XSI) and emit them as a plain-C header
# (asmdal_tables.h) for the asmdal.c port.
#
# The generated header is checked in so a normal build needs no Python; this
# generator is kept (like hollerith.py) for reproducibility.  Extracting the
# tables mechanically avoids hand-transcribing 378 octal opcodes by eye.
#
#   usage: python3 asmdal_tables.py [ASMDAL_SI61.XSI] [asmdal_tables.h]
#
# Note OPCODE_TABLE(0:377) is a *decimal* 0..377 bound => 378 entries.
import os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
src_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", ".original", "ASMDAL_SI61.XSI")
out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, "asmdal_tables.h")
src = open(src_path).read()


def between(text, start_anchor, end_anchor, frm=0):
    """Return text from start_anchor up to (not incl.) the first end_anchor."""
    i = text.index(start_anchor, frm)
    j = text.index(end_anchor, i)
    return text[i:j], j


opc = src[src.index("DCL 1 OPCODE_TABLE"):]
# Mnemonic lines end in "',"; the INIT list closes with "'),", so "),"
# first appears at the list terminator.
mn_block, _ = between(opc, "2 MNEMONIC", "),")
mnem = re.findall(r"'(.{6})'", mn_block)
# Each opcode line is BITBIN('nnn'O), -> contains ")," ; the list closes with
# "))," so that is the unambiguous terminator.
op_block, _ = between(opc, "2 OPCODE", ")),")
opval = re.findall(r"'([0-7]+)'O", op_block)
# The TYPE INIT list (single digits) closes with ");".
ty_block, _ = between(opc, "2 TYPE", ");")
types = re.findall(r"\b([0-3])\b", ty_block.split("INIT(", 1)[1])

jt = src[src.index("DCL 1 JSYS_TABLE"):]
jn_block, _ = between(jt, "2 NAME", "),")
jname = re.findall(r"'(.{6})'", jn_block)
jv_block, _ = between(jt, "2 NUMBER", "));")
jnum = re.findall(r"'([0-7]+)'O", jv_block.split("INIT(", 1)[1])

n = len(mnem)
assert n == 378, n
assert len(opval) == n and len(types) == n, (len(opval), len(types))
assert len(jname) == 65 and len(jnum) == 65, (len(jname), len(jnum))
# spot-checks against values read from the source by eye
assert (mnem[0], opval[0], types[0]) == ("ADD   ", "270", "0")
assert (mnem[377], opval[377]) == ("XORM  ", "432")
assert (mnem[206], opval[206], types[206]) == ("JSYS  ", "104", "2")  # JSYS instr
assert (opval[40], types[40]) == ("000", "1")                        # BLKI, I/O
assert (jname[0], jnum[0]) == ("BIN   ", "050")
assert (jname[64], jnum[64]) == ("WAIT  ", "306")

L = []
w = L.append
w("/* asmdal_tables.h - GENERATED by asmdal_tables.py from ASMDAL_SI61.XSI.")
w(" * Do not edit by hand; re-run the generator instead.")
w(" *")
w(" * OPCODE_TABLE: 378 PDP-10/DAL mnemonics (6 chars, blank padded, sorted")
w(" * for binary search), their 9-bit octal opcodes, and a type code")
w(" * (0 = normal, 1 = I/O, 2 = JSYS).  JSYS_TABLE: 65 JSYS aliases -> number.")
w(" * Reproduced verbatim from Dave Wagner's CP-6 ASMDAL so encodings match. */")
w("#ifndef ASMDAL_TABLES_H")
w("#define ASMDAL_TABLES_H")
w("")
w("#define NOPC %d" % n)
w("static const char op_mnem[NOPC][7] = {")
for i in range(0, n, 4):
    w("    " + ", ".join('"%s"' % mnem[j] for j in range(i, min(i + 4, n))) + ",")
w("};")
w("static const short op_val[NOPC] = {")
for i in range(0, n, 8):
    w("    " + ", ".join("0%s" % opval[j] for j in range(i, min(i + 8, n))) + ",")
w("};")
w("static const char op_type[NOPC] = {")
for i in range(0, n, 24):
    w("    " + ",".join(types[j] for j in range(i, min(i + 24, n))) + ",")
w("};")
w("")
w("#define NJSYS 65")
w("static const char jsys_name[NJSYS][7] = {")
for i in range(0, 65, 4):
    w("    " + ", ".join('"%s"' % jname[j] for j in range(i, min(i + 4, 65))) + ",")
w("};")
w("static const short jsys_num[NJSYS] = {")
for i in range(0, 65, 8):
    w("    " + ", ".join("0%s" % jnum[j] for j in range(i, min(i + 8, 65))) + ",")
w("};")
w("")
w("#endif")
open(out_path, "w").write("\n".join(L) + "\n")
print("wrote %s: %d opcodes, %d jsys" % (out_path, n, len(jname)))
