#!/usr/bin/env python3
# bmap_opcodes.py - extract the BMAP (CP-6 GMAP/DPS-8) op-code + pseudo-op
# table from BMAP_DA2.XSI and emit it as a plain-C header (bmap_opcodes.h).
#
# In the original build, BMAP_DA2 is the master op-code list fed (as M$UI) to
# BMAP_LINKOP (BMAP_SI64), which builds the op-code AVL tree in the SPOOL and
# substitutes it into BMAP_DA1's {OPS}/{OPROOT} templates to generate BMAP_C.
# For the C port we just need the table contents; the AVL packing is the
# original's storage detail (a sorted array + bsearch is equivalent).
#
# DA2 columnar format (see BMAP_SI64 NEXTOP, lines 117-138):
#     cols 0-5   MNEMONIC          (6-bit-ASCII packed symbol)
#     cols 8-13  VALUE   (octal)   -> OP.VAL (18 bits)
#     cols 16-21 FLAGS   (6 binary digits) = MASK(2) AR(1) RPL(1) PRFS(2)
#     col  24/25 TYPE    (decimal) -> OP.TYPE (0..45; see BMAP_DA1 lines 305-352)
#
#   usage: python3 bmap_opcodes.py [BMAP_DA2.XSI] [bmap_opcodes.h]
import os, sys

here = os.path.dirname(os.path.abspath(__file__))
src = (
    sys.argv[1]
    if len(sys.argv) > 1
    else os.path.join(here, "..", ".original", "BMAP_DA2.XSI")
)
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, "bmap_opcodes.h")

ops = []
seen = set()
for ln, line in enumerate(open(src), 1):
    if not line.strip():
        continue
    f = line.split()
    if len(f) != 4:
        raise SystemExit("DA2 line %d: expected 4 fields, got %r" % (ln, f))
    mnem, val_o, flags, typ = f
    assert mnem not in seen, "duplicate mnemonic %s (DA2 has unique names)" % mnem
    seen.add(mnem)
    val = int(val_o, 8)
    assert len(flags) == 6 and set(flags) <= {"0", "1"}, (ln, flags)
    mask = int(flags[0:2], 2)  # 1=octal modifier, 2=symbolic modifier
    ar = int(flags[2])  # AR field required
    rpl = int(flags[3])  # RPL instruction
    prfs = int(flags[4:6], 2)  # print flags: 2=octal, 1=location
    ops.append((mnem, val, mask, ar, rpl, prfs, int(typ)))

# sorted by mnemonic for binary search in the C port
ops.sort(key=lambda o: o[0])

# The 46 OP.TYPE codes (BMAP_DA1.XSI:305-352), kept for reference in the port.
TYPE_NAMES = [
    "IGNORE",
    "NON_EIS",
    "INDEX",
    "TALLY",
    "REPEAT",
    "RPTX_RPDX",
    "NO_VAR",
    "USE_BLOCK",
    "EJECT",
    "END",
    "INHIB",
    "BOUND",
    "ORG",
    "BOOL_EQU_SET",
    "DEF_REF",
    "ASCII",
    "DEC_OCT",
    "ZERO",
    "VFD_OPD",
    "DUP",
    "MACRO",
    "MACRO_CALL",
    "IF",
    "IO",
    "BSS",
    "IDCW",
    "CLIMB",
    "EIS",
    "BDSC",
    "ADSC",
    "NDSC",
    "MICROP",
    "ASCNT",
    "NSA_PTR",
    "NSA_VEC",
    "NSA_DESC",
    "NSA_ENTRY",
    "IDRP",
    "OPSYN",
    "LISTCTL",
    "OUNAME",
    "LODM",
    "EDEC",
    "ORGCSM",
    "DATE",
    "LIT",
]

L = []
w = L.append
w("/* bmap_opcodes.h - GENERATED by bmap_opcodes.py from BMAP_DA2.XSI.")
w(" * Do not edit by hand; re-run the generator instead.")
w(" *")
w(" * The CP-6 BMAP (GMAP / Honeywell 6000 / DPS-8 36-bit) op-code and")
w(" * pseudo-op table: %d entries, sorted by mnemonic for binary search." % len(ops))
w(" *   val  : OP.VAL (octal opcode bits, <=18 bits)")
w(" *   mask : modifier-field code (1=octal, 2=symbolic)")
w(" *   ar   : AR field required;  rpl: RPL instruction")
w(" *   prfs : print flags (2=octal, 1=location)")
w(" *   type : OP.TYPE 0..45 (see bmap_optype below / BMAP_DA1 lines 305-352) */")
w("#ifndef BMAP_OPCODES_H")
w("#define BMAP_OPCODES_H")
w("")
w(
    "struct bmap_op { const char *mnem; unsigned val; "
    "unsigned char mask, ar, rpl, prfs, type; };"
)
w("")
w("#define NBMAPOP %d" % len(ops))
w("static const struct bmap_op bmap_ops[NBMAPOP] = {")
for mnem, val, mask, ar, rpl, prfs, typ in ops:
    w(
        '    { "%s",%s0%o, %d, %d, %d, %d, %2d },'
        % (mnem, " " * (8 - len(mnem)), val, mask, ar, rpl, prfs, typ)
    )
w("};")
w("")
w("/* OP.TYPE names, indexed 0..45 */")
w("#define NBMAPTYPE %d" % len(TYPE_NAMES))
w("static const char *const bmap_optype[NBMAPTYPE] = {")
for i in range(0, len(TYPE_NAMES), 6):
    w("    " + ", ".join('"%s"' % t for t in TYPE_NAMES[i : i + 6]) + ",")
w("};")
w("")
w("#endif")
open(out, "w").write("\n".join(L) + "\n")
print("wrote %s: %d opcodes" % (out, len(ops)))
