#!/usr/bin/env python3
# bmap_asciitbl.py - extract BMAP's four character-conversion tables from the
# `ASCII CONSTANT SYMDEF` in BMAP_DA1.XSI and emit them as a plain-C header
# (bmap_asciitbl.h).  These map an ASCII source character to its GCOS BCD,
# EBCDIC, ASCII (identity) or 6-bit-ASCII code; the ASCII/BCI/EBCDIC/UASCI
# pseudo-ops (and VFD character fields) translate through them via XLATEV.
#
#   usage: python3 bmap_asciitbl.py [BMAP_DA1.XSI] [bmap_asciitbl.h]
import os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", ".original", "BMAP_DA1.XSI")
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, "bmap_asciitbl.h")

text = open(src).read()

def extract(name):
    # find  "2 NAME(0:511) UBIN(9) UNAL INIT( ... )"  and expand its items
    m = re.search(r"2\s+%s\(0:511\)[^\n]*?INIT\(" % re.escape(name), text)
    if not m:
        raise SystemExit("table %s not found" % name)
    i = m.end()
    depth = 1
    j = i
    while depth:                              # find the matching ')'
        if text[j] == '(': depth += 1
        elif text[j] == ')': depth -= 1
        j += 1
    body = text[i:j-1]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)   # strip PL/6 comments
    vals = []
    for item in body.replace("\n", " ").split(","):
        item = item.strip().rstrip(";")
        if not item:
            continue
        if "*" in item:                       # run-length: VALUE*COUNT
            v, c = item.split("*")
            vals += [int(v)] * int(c)
        else:
            vals.append(int(item))
    if len(vals) != 512:
        raise SystemExit("table %s: expected 512 entries, got %d" % (name, len(vals)))
    return vals

tables = [("bcd", extract("BCD")), ("ebcdic", extract("EBCDIC")),
          ("ascii", extract("ASCII")), ("ascii6", extract("ASCII6"))]

L = []
w = L.append
w("/* bmap_asciitbl.h - GENERATED by bmap_asciitbl.py from BMAP_DA1.XSI.")
w(" * Do not edit by hand; re-run the generator instead.")
w(" *")
w(" * BMAP's four ASCII-source -> code conversion tables (512 entries each),")
w(" * indexed 0..3 by OP.VAL as `bmap_asciit[OP.VAL]`:")
w(" *   0 = GCOS BCD, 1 = EBCDIC, 2 = ASCII (identity), 3 = 6-bit ASCII.")
w(" * Used by XLATEV for the ASCII/BCI/EBCDIC/UASCI pseudo-ops and VFD. */")
w("#ifndef BMAP_ASCIITBL_H")
w("#define BMAP_ASCIITBL_H")
w("")
w("static const unsigned short bmap_asciit[4][512] = {")
for name, vals in tables:
    w("    {   /* %s */" % name)
    for k in range(0, 512, 16):
        w("    " + " ".join("%3d," % v for v in vals[k:k+16]))
    w("    },")
w("};")
w("")
w("#endif")
open(out, "w").write("\n".join(L) + "\n")
print("wrote %s: 4 tables x 512 entries" % out)
